### PR TITLE
Dump all responses, before bailing out for non-successful http status codes

### PR DESCRIPTION
**Pull request by nvartolomei**

### CODE REVIEW

**Comment by connor4312** [comment]
Any chance of getting this in @olivere? This is a simple change that makes debugging errors a whole lot easier! 😄

**Comment by olivere** [comment]
I'm busy at work. I will try to spend an afternoon on all open issues later this week.

**Comment by olivere** [comment]
Will be part of 5.0.42 later today.

**Comment by connor4312** [comment]
Awesome, thanks!

**Pull request merged**
