### PR TITLE
solve incorrect response field for search suggestion

### PR DESCRIPTION
**Pull request by misterciput**
Can not get score and frequency of suggestion when using search suggestion.
Caused by parsing wrong json field. We see that in elasticsearch raw search suggestion option response will be like this:

`"options": [
    {
           "text": "shoes",
           "score": 0.8,
           "freq": 34084
     }
 ]
`
and the code parse "_score" and did not parse "freq"
This PR fix this by change the field we parse into correct field

### CODE REVIEW

**Comment by olivere** [comment]
Thank you. This will of course be fixed in the next version. I will look the structures up in the Java code. Maybe there's some other fields missing / renamed.

**Comment by olivere** [comment]
I did have a look at this and added/modified the response in accordance with [Suggest.Option](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/search/suggest/Suggest.java#L621). I couldn't find a `freq` field there. I know the [documentation page](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/search-suggesters.html) lists it, but it doesn't seem to be in the code any more. Did you really get that with a query in 5.6.3?

Anyway, I will push 5.0.49 soon.

Thanks for being a contributor to Elastic and open source in general. 👍

**Comment by misterciput** [comment]
Sure, I really get the `freq` field when I do terms suggestion query like this

```
{
  "suggest" : {
	"suggestion": {
		"text": "shues",
		"term": {
			"analyzer": "whitespace",
			"field": "ad_title",
			"min_doc_freq": 1,
			"size": 1,
			"suggest_mode": "popular"
		}
	}
  }
}
```

I think the code is not in [Suggest.Option](https://github.com/elastic/elasticsearch/blob/5.5/core/src/main/java/org/elasticsearch/search/suggest/Suggest.java#L621) but it still exist in [TermSuggestion.Option](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/search/suggest/term/TermSuggestion.java#L178), maybe you can check about this. It should be related to https://github.com/olivere/elastic/issues/497 that every suggestion (terms, phrase, and completion) has different response. I still find a best way to refactor each type of suggestion into a better one.

It is a great honor to contribute in Elastic

**Comment by olivere** [comment]
@misterciput Ah, I see. Yes, Suggesters need to be refactored to do this cleanly. In the meantime, I should simply add this field and aggregate all all possible returns values.

**Comment by misterciput** [comment]
@olivere Yes that should be useful for this time. Still didn't know why elastic have different response in each suggestion like in using `_score` in completion suggester but use `score` in phrase and terms suggester.

**Comment by olivere** [comment]
@misterciput You mean Elastic has that, or Elasticsearch?

**Comment by misterciput** [comment]
Sorry I mean Elasticsearch

**Comment by olivere** [comment]
@misterciput Yeah. Elastic, this library, had that name even before Elastic, the company, was established :-)

It's quite hard to manage such a huge API. Things always drift apart, so I fully understand why that happens from time to time. But they usually fix it in new releases.

**Comment by misterciput** [comment]
@olivere amazing :-)

Yeah, But it is some kind of fun to have an amazing API like this, a lot of better than golang API from elasticsearch itself.

It will be great if I can see the updated `freq` field in the next release, I have tested it by this commit and no something weird happen.

**Comment by olivere** [comment]
Yeah. I will push 5.0.52 in a minute.

**Comment by misterciput** [comment]
@olivere great, thanks a lot

**Pull request closed without merging**
