### PR TITLE
Putuserv6

### PR DESCRIPTION
**Pull request by sangeethdba**

### CODE REVIEW

**Review by olivere — CHANGES_REQUESTED** [review]
Can you please fix the imports: You're in the `release-branch.v6` referencing `v7` in `xpack_security_put_user.go`.

Can you also double-check that parameters for XPack Put User API didn't change between v6 and v7.

Otherwise, it should be OK.

**Comment by sangeethdba** [comment]
github.com/olivere/elastic/uritemplates
++++++v7++++++
curl -X POST "localhost:9200/_security/role/my_admin_role?pretty" -H 'Content-Type: application/json' -d'
{
  "cluster": ["all"],
  "indices": [
    {
      "names": [ "index1", "index2" ],
      "privileges": ["all"],
      "field_security" : { // optional
        "grant" : [ "title", "body" ]
      },
      "query": "{\"match\": {\"title\": \"foo\"}}" // optional
    }
  ],
  "applications": [
    {
      "application": "myapp",
      "privileges": [ "admin", "read" ],
      "resources": [ "*" ]
    }
  ],
  "run_as": [ "other_user" ], // optional
  "metadata" : { // optional
    "version" : 1
  }
}
'
 +++++v6+++++++
curl -X POST "localhost:9200/_xpack/security/role/my_admin_role?pretty" -H 'Content-Type: application/json' -d'
{
  "cluster": ["all"],
  "indices": [
    {
      "names": [ "index1", "index2" ],
      "privileges": ["all"],
      "field_security" : { // optional
        "grant" : [ "title", "body" ]
      },
      "query": "{\"match\": {\"title\": \"foo\"}}" // optional
    }
  ],
  "applications": [
    {
      "application": "myapp",
      "privileges": [ "admin", "read" ],
      "resources": [ "*" ]
    }
  ],
  "run_as": [ "other_user" ], // optional
  "metadata" : { // optional
    "version" : 1
  }
}
'

**Comment by olivere** [comment]
I will include it in 6.2.36, which will be published in a few minutes. Thank you.

**Comment by sangeethdba** [comment]
thank you so much .

**Pull request closed without merging**
