### PR TITLE
Master

### PR DESCRIPTION
**Pull request by superb80s**

### CODE REVIEW

**Comment by superb80s** [comment]
getSource

**Comment by superb80s** [comment]
getSource

**Comment by olivere** [comment]
You don't want to do it this way. If we need the `SearchSource`, you [create one](https://github.com/olivere/elastic/blob/release-branch.v7/search_source.go#L49-L57) and [pass it into the `SearchService`](https://github.com/olivere/elastic/blob/release-branch.v7/search.go#L104-L111). It's the other way around.

**Comment by superb80s** [comment]
thx

**Pull request closed without merging**
