### PR TITLE
Fix tracelog issue with large requests/responses

### PR DESCRIPTION
**Pull request by gdm85**
There is a limitation in bufio that prevents current trace dumps to work:
```
time="2015-11-30T14:50:01+01:00" level=info msg="ES trace 2015/11/30 14:50:01 GET /_all/_settings HTTP/1.1" 
time="2015-11-30T14:50:01+01:00" level=info msg="Host: x.x.x.x:9200" 
time="2015-11-30T14:50:01+01:00" level=info msg="User-Agent: elastic/2.0.20 (linux-amd64)" 
time="2015-11-30T14:50:01+01:00" level=info msg="Accept: application/json" 
time="2015-11-30T14:50:01+01:00" level=info msg="Accept-Encoding: gzip" 
time="2015-11-30T14:50:01+01:00" level=info msg= 
time="2015-11-30T14:50:01+01:00" level=info msg= 
time="2015-11-30T14:50:01+01:00" level=info msg="ES trace 2015/11/30 14:50:01 HTTP/1.1 20
0 OK" 
time="2015-11-30T14:50:01+01:00" level=info msg="Content-Length: 191369" 
time="2015-11-30T14:50:01+01:00" level=info msg="Content-Type: application/json; charset=UTF-8" 
time="2015-11-30T14:50:01+01:00" level=info msg= 
time="2015-11-30T14:50:01+01:00" level=error msg="Error while reading from Writer: bufio.Scanner: token too long" 
time="2015-11-30T14:50:01+01:00" level=info msg="ES info 2015/11/30 14:50:01 GET http://x.x.x.x:9200/_all/_settings [status:200, request:0.065s]" 
time="2015-11-30T14:50:01+01:00" level=fatal msg="elastic: Error 400 (Bad Request)" component="cmd/es-index-deploy" hostname=xxx
```

You can find the constant precisely at line 71 here: https://golang.org/src/bufio/scan.go (being 64K)

When the user is troubleshooting issue #170 he/she can't get any help from log traces because of this problem. By using the trace method I introduce here, will instead be able to see the large request and provide/use it as a testcase.

### CODE REVIEW

**Comment by olivere** [comment]
@gdm85 TBH I'm not sure I want to enable this by default. Don't misunderstand me: I know what you're after, and I see how it can be valuable. However, it can also result in GB of log file data without even noticing. Maybe by introducing a verbosity level? I personally think elastic is already too verbose by default.

**Comment by gdm85** [comment]
@olivere as it is now, it has an (undocumented) limitation/feature that goes more or less like this:
* bufio has a 64K scan limitation, so anything larger than 64K will result in an error being printed instead of the actual HTTP requests/responses

You could either document this in a KNOWN_BUGS file, or allow this to be configured, or leave to the user the problem of the GBs in the logs.

I do not think it is the job of the client library to take care of verbose output when you enable such verbose output, but rather if the client library can help in "seeing" what goes on behind curtains, that shall be the biggest priority as without it you simply are stuck, and need to use tcpdump/wireshark instead.

**Comment by olivere** [comment]
@gdm85 Can you write a test that illustrates the issue in elastic and how your PR changes that?

**Comment by gdm85** [comment]
@olivere sure, I will send it in a few hours

**Comment by gdm85** [comment]
I am having some issues at reproducing the problem; I am progressively increasing the generated response size until I can reproduce it.

**Comment by olivere** [comment]
Same here. I tried to reproduce it by writing to `bytes.Buffer` but it logged just fine at any arbitrary size. So I asked to see if you could find a reproducible test.

**Comment by olivere** [comment]
@gdm85 Sorry to bother you, but I'm cleaning up issues. Did you have success in reproducing the issue recently?

**Comment by gdm85** [comment]
No you're right, sorry for not coming back on this.
I will open it again if problem is found and there is a testcase.

**Pull request closed without merging**
