### PR TITLE
Add SetRawSource to ScanService

### PR DESCRIPTION
**Pull request by aliphen**
SearchService has a Source(query interface{}) method, useful for
performing direct requests crafted somewhere else in the code.
Having this available in ScanService is similarly useful.

### CODE REVIEW

**Comment by olivere** [comment]
Thanks for contributing.

I will have to see if that makes sense for `Scan`, because `Scan` and `Scroll` in v2 really need access to the body to do what they are supposed to do.

BTW: I've switched to using `Body` as the function name to do that in other services, e.g. [`ScrollService`](https://github.com/olivere/elastic/blob/release-branch.v5/scroll.go#L93-L100) in 5.0. Then it won't collide with e.g. this [`Source`](https://github.com/olivere/elastic/blob/release-branch.v5/query.go).

**Comment by aliphen** [comment]
Thanks for the review ! I do think it makes sense, it just means that it's really up to the user to provide a valid body. The interface name change is a good idea IMO.

Cheers !

**Comment by aliphen** [comment]
Hi,
just for planning purposes, could you give me a very rough estimate of when you expect to merge (or close) this ? No hurry, I just don't know how often you have time to work on this so I figured I'd ask.
Thanks for your work on the lib !

**Comment by olivere** [comment]
Hi there. I've not merged this on the weekend because it seems you're trying to get this into v2 which is in maintenance mode really. Is it correct you still need support for ES 1.x? It's very very stable, no problem, just asking.

I can try to get this in later in the evening. It's not too much work after all.

**Comment by olivere** [comment]
The Travis build for 2.0.56 is running. Once it succeeds, I'll tag the release and you should be able to `go get -u gopkg.in/olivere/elastic.v2`.

Thanks for supporting Elastic.

**Comment by aliphen** [comment]
Thank you for the quick answer and the merge !

**Pull request closed without merging**
