### PR TITLE
add quote_field_suffix to simple_query_string

### PR DESCRIPTION
**Pull request by slawo**
fix for #750

### CODE REVIEW

**Comment by slawo** [comment]
It has been tested in an internal project

**Comment by olivere** [comment]
Looking good. I will add it in the next release. I typically use these "bugs" as a chance to look into the Java code for other missing/removed properties. So it'll take a few days more.

**Comment by slawo** [comment]
If you want I can complete all the other missing properties from es6.2

**Comment by olivere** [comment]
Thanks for your support. It's basically synchronizing the Go code with [`QueryStringQueryBuilder.java`](https://github.com/elastic/elasticsearch/blob/v6.2.3/server/src/main/java/org/elasticsearch/index/query/QueryStringQueryBuilder.java) and [`SimpleQueryStringBuilder.java`](https://github.com/elastic/elasticsearch/blob/v6.2.3/server/src/main/java/org/elasticsearch/index/query/SimpleQueryStringBuilder.java).

But, to be honest, I think I'd like to do this myself. That way it's slower, but I keep myself in touch with the changes in core.

**Comment by slawo** [comment]
OK, no wories

**Comment by olivere** [comment]
Thanks again.

**Pull request merged**
