### PR TITLE
add AllowPartialSearchResults for SearchService

### PR DESCRIPTION
**Pull request by NikitaSerenko**

### CODE REVIEW

**Comment by NikitaSerenko** [comment]
Hello, olivere!
This little parameter can save my day!
I made it like SearchRequest::allowPartialSearchResults

**Comment by olivere** [comment]
Aw yeah, [here it is](https://github.com/elastic/elasticsearch/blob/6.8/rest-api-spec/src/main/resources/rest-api-spec/api/search.json#L154-L158). I will do this in the next release and do a forward-port to 7.x. When I'm in the process of doing this, I will see if there are other parameters missing as well.

**Comment by NikitaSerenko** [comment]
Thanks for the fast reply, great news to hear!
Can you give an approximate date of release for this feature, please?

**Comment by olivere** [comment]
Maybe over the weekend. But I'm still doing this in my spare time, so I tend to not take deadlines too seriously.

**Comment by olivere** [comment]
Implemented in 6.2.25 and 7.0.8.

**Pull request closed without merging**
