### PR TITLE
Snapshot Restore Service

### PR DESCRIPTION
**Pull request by alejandro-carstens**
Hi, first of all thanks for developing this project. It is awesome. Secondly, I took the liberty of writing the SnapshotRestoreService which I saw was pending. Please let me know your thoughts, I wrote tests plus tested it manually with all its parameters and works as expected.

Thanks in advance and have a nice day,

Alejandro

### CODE REVIEW

**Comment by olivere** [comment]
Thanks! 🚀 Will review for 7.0.2 and 6.2.19.

**Comment by olivere** [comment]
You have a lot more parameters than specified in the [REST API spec](https://github.com/elastic/elasticsearch/blob/7.1/rest-api-spec/src/main/resources/rest-api-spec/api/snapshot.restore.json). Where do you have them from?

**Comment by olivere** [comment]
OK. I see. They're part of the [request body](https://github.com/elastic/elasticsearch/blob/7.1/server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java), which isn't specified (same with the response). So, looks okay when comparing with the Java code.

**Comment by alejandro-carstens** [comment]
Awesome, appreciate it. Let me know if anything pops up, and I'll address it.

**Comment by olivere** [comment]
Merged and released in 6.2.19 and 7.0.2.

**Comment by alejandro-carstens** [comment]
Thanks Olivere!

**Pull request closed without merging**
