### PR TITLE
fix bug

### LINKED ISSUE #1355: Elasticsearch 5.x  NewCompletionSuggester 返回score 为0
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[*] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
在用 NewCompletionSuggester  发现返回结果得分全部为0
 
### Please describe the actual behavior
源码search.go 中

// SearchSuggestionOption is an option of a SearchSuggestion.
// See https://www.elastic.co/guide/en/elasticsearch/reference/5.6/search-suggesters.html.
type SearchSuggestionOption struct {
	Text         string           `json:"text"`
	Index        string           `json:"_index"`
	Type         string           `json:"_type"`
	Id           string           `json:"_id"`
	Score        float64          `json:"score"`
	Highlighted  string           `json:"highlighted"`
	CollateMatch bool             `json:"collate_match"`
	Freq         int              `json:"freq"` // from TermSuggestion.Option in Java API
	Source       *json.RawMessage `json:"_source"`
}

### Any steps to reproduce the behavior?
Score        float64          `json:"score"`  应该 为   Score        float64          `json:"_score"`

### PR DESCRIPTION
**Pull request by linzhenlong**
Fixes #1355 https://github.com/olivere/elastic/issues/1355

### CODE REVIEW

**Comment by linzhenlong** [comment]
fix

**Comment by olivere** [comment]
That's probably too simple, as I think older versions of ES 5.x use `score`, while newer versions use `_score`. We had the same with ES 6.x.

**Comment by owenliang** [comment]
I have also encountered this problem recently, could we merge the PR, thanks. @olivere

**Comment by olivere** [comment]
Fixed by #1364

**Pull request closed without merging**
