### PR TITLE
Support _nodes/stats for elasticsearch 1.x series.

### PR DESCRIPTION
**Pull request by jdelgad**
Follow pattern in nodes_info.go.

### CODE REVIEW

**Comment by jdelgad** [comment]
Pending acceptance I plan to issue a PR for v3 supporting elasticsearch 2.x.

**Comment by olivere** [comment]
Thank you. I'll hopefully find some time over the weekend for review.

You could double-check that the API contains all properties defined in the [REST API spec](https://github.com/elastic/elasticsearch/tree/2.4/rest-api-spec) for that endpoint.

Also notice that there is a Go generator that builds a skeleton for API's based on the REST API spec. You can find it in the [`generate-api` branch](https://github.com/olivere/elastic/tree/generate-api/generator). No need to implement everything manually. :-)

**Comment by jdelgad** [comment]
@olivere I've found a few discrepancies. I'll mention you again when all of the API spec has been met.

**Comment by olivere** [comment]
Take your time. I'll be out of office for a few days anyway.

**Comment by jdelgad** [comment]
@olivere Added unit test similar to that of what is already in the repo. Implemented the REST API and included it in the commit message based on https://github.com/elastic/elasticsearch/blob/1.7/rest-api-spec/api/nodes.stats.json

I did notice that the `groups` parameter is marked as a `boolean`, although it is a list as referenced in its documentation https://www.elastic.co/guide/en/elasticsearch/reference/1.7/cluster-nodes-stats.html

**Comment by olivere** [comment]
I'm sorry. I cannot merge this. There are a few problems.

First, please remove the `iota` values for `Level`. I tried that a few years ago, and it's just not worth it in the client. Simply let the caller pass a `string`.

Second, the Nodes Stats API has many endpoints. You need to use the one that matches the parameters given by the caller. You always assume `/_nodes/{node_id}/stats/{metric}/{index_metric}` is okay to use. But that doesn't work when `{node_id}` or `{metric}` isn't specified by the caller. We need to take this into consideration.

Third, although I didn't check in detail: Many of the structures returned by Nodes Stats API are already returned by Nodes Info API as well. I guess I have to figure out if duplicating the structs is really the better approach.

I'm thankful for your support. But it's hard to keep on top of all the endpoints ES provides and still keep everything under control. I think we'll have to have another round on Nodes Stats API.

**Comment by jdelgad** [comment]
Comment 1 I've addressed, but will wait to put it up for now.

For comment 2 I'm a bit confused. Looking at https://github.com/olivere/elastic/blob/release-branch.v2/nodes_info.go#L85 I'm doing the same here https://github.com/olivere/elastic/pull/314/files#diff-3910d97348111eb8bb2b1710f118a56dR156

When `{node_id}` or `{metric}` isn't specified, then `_all` is used in its place. Perhaps I'm not understanding. Can you give me a code example using my PR so I can understand what you are saying doesn't work?

Question 3, I have time to work on merging the two. Just let me know what you would like and I'll go forward. Once we have this solidified for ES 1.x then I'll continue working on the ES 2.x branch.

**Comment by olivere** [comment]
Sorry for the delay.

Regarding comment 2: I didn't see that you initialized `metric` and `nodeId` with `"_all"` in the initializer. Sorry for that.

Re question 3, it looks like both endpoints return the same structures. What needs to be done is first to check if that's a correct assumption by looking at the Java source code. It takes some experience to find the correct reference in the [elasticsearch repository](https://github.com/elastic/elasticsearch) (use the current `2.x` branch for elastic.v3). Then we'd need to check if the properties in our structs are in sync with those in the Java source.

I'll eventually do that, too. No worries if you don't feel like you can do that. Unfortunately, I'm rather busy at the moment, so it'll take some time.

**Comment by olivere** [comment]
Backport should be available in 2.0.54.

**Pull request closed without merging**
