### PR TITLE
Add track total hits releasev6.8

### PR DESCRIPTION
**Pull request by amanjain97**
This PR is to add trackTotalHits parameter to SearchService
Regarding issue #1276

Please guide me if I need to add something else.

### CODE REVIEW

**Review by olivere — APPROVED** [review]
LGTM

**Comment by olivere** [comment]
This looks good and will be merged in the next v6 release. Will have to port it to v7 as well though.

**Comment by amanjain97** [comment]
@olivere Thanks for the review. 
Do we have to make a separate PR for v7 too.

**Comment by olivere** [comment]
Yes, unfortunately we have to.

**Comment by olivere** [comment]
Fixed in next release of v6.

**Pull request closed without merging**
