### PR TITLE
Added Geo Centroid aggregation + minimal tests

### PR DESCRIPTION
**Pull request by Zyqsempai**
Added Geo Centroid aggregation + minimal tests
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-geocentroid-aggregation.html

### CODE REVIEW

**Comment by Zyqsempai** [comment]
Oh, i forgot about search_aggs_test, i will add them to this PR soon.

**Comment by olivere** [comment]
Yeah. Aggregations are a beast. It's both serialization and deserialization.

Can you add an integration test for the new aggregation to [TestSearchAggs](https://github.com/olivere/elastic/blob/release-branch.v6/search_aggs_test.go#L15) as well. It contains all aggregation types and makes sure that it works against "the real thing (tm)" :-)
 
Good work!

**Comment by olivere** [comment]
BTW: To debug tests, simply enable logging by switching e.g. [the comments in these two lines](https://github.com/olivere/elastic/blob/release-branch.v6/search_aggs_test.go#L16-L17).

**Comment by Zyqsempai** [comment]
I suppose that's all, please check if i didn't forget anything.

**Comment by olivere** [comment]
Yep, looking good 👍 

Will merge all PRs in the next release. Thanks for supporting open source.

**Pull request merged**
