### PR TITLE
span near query was added

### PR DESCRIPTION
**Pull request by pzentenoe**
I added span near query for need of use. you could check if it is feasible to upload this and generate a new olivere release

### CODE REVIEW

**Comment by olivere** [comment]
It goes into the right direction. I always use the Java source as the ultimate source of truth. For `SpanNearQuery`, that's [this file](https://github.com/elastic/elasticsearch/blob/v7.7.0/server/src/main/java/org/elasticsearch/index/query/SpanNearQueryBuilder.java).

**Comment by pzentenoe** [comment]
modify the name of the files based on what you sent me and create the builder methods

**Comment by pzentenoe** [comment]
could you check again? please

**Comment by olivere** [comment]
Thanks for your work. I will add a few more Span queries in a different branch with 7.0.17 and 6.2.33.

**Pull request closed without merging**
