### PR TITLE
elastic.v5: Run `GO111MODULE=on go mod tidy'

### PR DESCRIPTION
**Pull request by VojtechVitek**
I noticed lot of weird packages being pulled by `gopkg.in/olivere/elastic.v5 v5.0.73`.

This PR removes these false positives in go.mod and go.sum with `GO111MODULE=on go mod tidy` command.

Note: I'm using `go version go1.11rc1 darwin/amd64`

### CODE REVIEW

**Comment by VojtechVitek** [comment]
FYI, I tried the same on v6 release branch and there was no diff 👍

**Comment by olivere** [comment]
Hmm... I did that on the v5 release and my results, with go1.11rc1 are different. Have to figure out why that happens.

Here's my outcome:

```
$ GO111MODULE=on go1.11rc1 mod tidy
$ cat go.mod
module gopkg.in/olivere/elastic.v5

require (
	github.com/Sirupsen/logrus v1.0.6
	github.com/davecgh/go-spew v1.1.1 // indirect
	github.com/fortytw2/leaktest v1.2.0
	github.com/fsnotify/fsnotify v1.4.7 // indirect
	github.com/golang/protobuf v1.1.0 // indirect
	github.com/google/uuid v0.0.0-20171129191014-dec09d789f3d
	github.com/hpcloud/tail v1.0.0 // indirect
	github.com/kr/pretty v0.1.0 // indirect
	github.com/mailru/easyjson v0.0.0-20180730094502-03f2033d19d5
	github.com/olivere/elastic v6.1.25+incompatible
	github.com/olivere/env v1.0.0
	github.com/onsi/ginkgo v1.6.0 // indirect
	github.com/onsi/gomega v1.4.1 // indirect
	github.com/pkg/errors v0.8.0
	github.com/pmezard/go-difflib v1.0.0 // indirect
	github.com/russross/blackfriday v2.0.0+incompatible
	github.com/shurcooL/sanitized_anchor_name v0.0.0-20170918181015-86672fcb3f95 // indirect
	github.com/sirupsen/logrus v1.0.6 // indirect
	github.com/smartystreets/assertions v0.0.0-20180803164922-886ec427f6b9 // indirect
	github.com/smartystreets/go-aws-auth v0.0.0-20180515143844-0c1422d1fdb9
	github.com/smartystreets/gunit v0.0.0-20180314194857-6f0d6275bdcd // indirect
	github.com/stretchr/testify v1.2.2 // indirect
	golang.org/x/crypto v0.0.0-20180816225734-aabede6cba87 // indirect
	golang.org/x/net v0.0.0-20180816102801-aaf60122140d
	golang.org/x/sync v0.0.0-20180314180146-1d60e4601c6f
	golang.org/x/sys v0.0.0-20180816055513-1c9583448a9c // indirect
	golang.org/x/text v0.3.0 // indirect
	gopkg.in/airbrake/gobrake.v2 v2.0.9 // indirect
	gopkg.in/check.v1 v1.0.0-20180628173108-788fd7840127 // indirect
	gopkg.in/fsnotify.v1 v1.4.7 // indirect
	gopkg.in/gemnasium/logrus-airbrake-hook.v2 v2.1.2 // indirect
	gopkg.in/olivere/elastic.v3 v3.0.74
	gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7 // indirect
	gopkg.in/yaml.v2 v2.2.1 // indirect
)
```

**Comment by olivere** [comment]
This should be the minimal `go.mod` required for `elastic.v5`. I generated it with:

```
$ rm go.mod go.sum
$ GO111MODULE=on go1.11rc1 test . ./aws/... ./config/...
go: creating new go.mod: module gopkg.in/olivere/elastic.v5
go: finding github.com/smartystreets/go-aws-auth latest
go: finding github.com/mailru/easyjson/jwriter latest
go: finding github.com/mailru/easyjson/jlexer latest
go: finding github.com/mailru/easyjson latest
ok  	gopkg.in/olivere/elastic.v5	65.212s
ok  	gopkg.in/olivere/elastic.v5/aws	(cached)
ok  	gopkg.in/olivere/elastic.v5/config	(cached)
$ cat go.mod
module gopkg.in/olivere/elastic.v5

require (
	github.com/fortytw2/leaktest v1.2.0
	github.com/mailru/easyjson v0.0.0-20180730094502-03f2033d19d5
	github.com/pkg/errors v0.8.0
	github.com/smartystreets/go-aws-auth v0.0.0-20180515143844-0c1422d1fdb9
)
$ cat go.sum
github.com/fortytw2/leaktest v1.2.0 h1:cj6GCiwJDH7l3tMHLjZDo0QqPtrXJiWSI9JgpeQKw+Q=
github.com/fortytw2/leaktest v1.2.0/go.mod h1:jDsjWgpAGjm2CA7WthBh/CdZYEPF31XHquHwclZch5g=
github.com/mailru/easyjson v0.0.0-20180730094502-03f2033d19d5 h1:0x4qcEHDpruK6ML/m/YSlFUUu0UpRD3I2PHsNCuGnyA=
github.com/mailru/easyjson v0.0.0-20180730094502-03f2033d19d5/go.mod h1:C1wdFJiN94OJF2b5HbByQZoLdCWB1Yqtg26g4irojpc=
github.com/pkg/errors v0.8.0 h1:WdK/asTD0HN+q6hsWO3/vpuAkAr+tw6aNJNDFFf0+qw=
github.com/pkg/errors v0.8.0/go.mod h1:bwawxfHBFNV+L2hUp1rHADufV3IMtnDRdf1r5NINEl0=
github.com/smartystreets/go-aws-auth v0.0.0-20180515143844-0c1422d1fdb9 h1:hp2CYQUINdZMHdvTdXtPOY2ainKl4IoMcpAXEf2xj3Q=
github.com/smartystreets/go-aws-auth v0.0.0-20180515143844-0c1422d1fdb9/go.mod h1:SnhjPscd9TpLiy1LpzGSKh3bXCfxxXuqd9xmQJy3slM=
```

**Comment by VojtechVitek** [comment]
@olivere This doesn't seem right to me.

Trying from scratch:
```
$ git clone https://github.com/olivere/elastic.git --branch=release-branch.v5
$ cd elastic
$ GO111MODULE=on go mod tidy
```

Note that the latest commit that I just pushed adds bunch of dependencies. In fact, I can `git grep` them in the codebase too, ie.

```
$ git grep 'github.com/google/uuid'
recipes/bulk_processor/main.go:26:  "github.com/google/uuid"
```

**Comment by olivere** [comment]
Yep. But `./recipes` isn't strictly required to use `gopkg.in/olivere/elastic.v5` as a Go client for Elasticsearch. It's just a list of examples I could easily put in a different repository (where they would get lost and nobody would see them). So I guess it'd be the best approach to only include the minimal set of "required" dependencies, no?

**Comment by VojtechVitek** [comment]
@olivere I see what you mean. Yeah, that makes sense. Thanks

I'll try out latest tag and report back.

**Comment by VojtechVitek** [comment]
Please let me know when new tag is available.

**Comment by olivere** [comment]
Give me a second...

Can you please try with `v5.0.74`? I'd love to get Go modules figured out finally.

**Comment by VojtechVitek** [comment]
```
$ GO111MODULE=on go get -u=patch
go: finding gopkg.in/olivere/elastic.v5 v5.0.74

$ git status

	modified:   go.mod
	modified:   go.sum
	modified:   vendor/gopkg.in/olivere/elastic.v5/client.go
	modified:   vendor/gopkg.in/olivere/elastic.v5/config/config.go
	modified:   vendor/gopkg.in/olivere/elastic.v5/search_queries_simple_query_string.go
	modified:   vendor/gopkg.in/olivere/elastic.v5/snapshot_create_repository.go
```

It works now! I don't see any unnecessary dependencies anymore. Thanks!

**Pull request closed without merging**
