### PR TITLE
Add support for gzip compression

### PR DESCRIPTION
**Pull request by adamweiner**
Added support for sending gzip compressed requests to Elasticsearch.

For this feature to work, elasticsearch.yml must include `http.compression: true`

Let me know if there's anything you'd like to see changed, I'm happy to make modifications.

### CODE REVIEW

**Comment by olivere** [comment]
Awesome. I'm busy this week, but I'll definitely have a look at the weekend. Thanks.

**Comment by olivere** [comment]
@adamweiner Hi! I've played around with your PR, refactored the code a bit and all tests work fine. You can find it in the [gzip branch](https://github.com/olivere/elastic/tree/gzip). Can you have a look at the changes and test the branch again? (Best way to test is probably to set `DefaultGzipEnabled = true` in `client.go`). Also: I've used elastic.v3 as a basis, so please use ES 2.0.

**Comment by adamweiner** [comment]
Hey - the refactored code looks great. I just tested the gzip branch (with elastic.v3/ES 2.0) and it seems to be working just fine. All my testing prior to your refactor was done using elastic.v2/ES 1.7 as a basis, so I'd venture to say the feature is good to go!

**Comment by adamweiner** [comment]
Also just to confirm, this will be merged into v2 as well as v3 once deemed ready, correct?

**Comment by olivere** [comment]
Yep. Both v2 and v3. Will have to wait a few more days unfortunately...

**Comment by olivere** [comment]
I just pushed new releases that support gzip compression both [for 2.0](https://github.com/olivere/elastic/commit/444684342d4c12c7c05bed13bd249034370840a9) and [for 3.0](https://github.com/olivere/elastic/commit/c3762bc7868c446b1fe2b689652651d8642f02ec).

**Comment by adamweiner** [comment]
Awesome, thanks! :+1:

**Pull request closed without merging**
