### PR TITLE
Added Diversified Sampler Aggs + tests

### PR DESCRIPTION
**Pull request by Zyqsempai**
Added Diversified Sampler Aggs + tests
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-diversified-sampler-aggregation.html

### CODE REVIEW

**Comment by olivere** [comment]
Once again, I appreciate spending your time and work for elastic. Looks like we're getting closer to feature complete ;-)

I hope to release a new version soon, which will include all your PRs.

**Comment by olivere** [comment]
All PRs merged. Release is due soon. Thanks again for your fantastic support.

**Comment by Zyqsempai** [comment]
Hi, glad to hear it, and your welcome))
I have in plans to complete all missing APis, what do you think about CAT API, maybe the time is come to implement it?

**Comment by olivere** [comment]
@Zyqsempai To be honest, I think the `_cat` endpoint is for end-users, not for clients.

What I think would help many users is to add [X-Pack](https://www.elastic.co/guide/en/x-pack/current/xpack-introduction.html) to the Elastic, at least info, security, alerting and monitoring. With ES 6.3, most of [X-Pack will become open](https://www.elastic.co/blog/doubling-down-on-open).

There's an [issue](https://github.com/olivere/elastic/issues/476) to track X-Pack, but I simply don't have the time for it now. The official Elasticsearch .NET client has API spec files for X-Pack; I don't know if they are outdated now. I [asked in the Elasticsearch forums](https://discuss.elastic.co/t/rest-api-spec-available-for-x-pack/80037) a while ago and got a link; but maybe they will open it up to the public once X-Pack will become open.

Maybe we can add it to `github.com/olivere/elastic/xpack` to keep it separate from the core client (I'm not sure if that'll work out of the box due though).

**Comment by Zyqsempai** [comment]
Great idea, X-Pack is really useful, i will check all the resources and if i'l find something i will open an issue and we will discuss it more detailed.

**Pull request merged**
