### PR TITLE
#23 - phrase_suggest candidate generator types

### PR DESCRIPTION
**Pull request by nizsheanez**

### CODE REVIEW

**Comment by olivere** [comment]
Can you please test the [refactor-suggesters](https://github.com/olivere/elastic/tree/refactor-suggesters) branch. It comes with candidate generators. Furthermore, it brings all suggesters to ES 1.4 level.

**Comment by nizsheanez** [comment]
aha! didn't see. 
what the status of the refactor-suggesters branch? need some help?

**Comment by olivere** [comment]
No. The refactor-suggesters branch is just so big that I need someone to test it with real code. And you asked for it, so... ;-)

Notice that the branch breaks the API (e.g. property `Smoothing` of type `interface{}` has changed to `SmoothingModel` with `SmoothingModel` (an interface). I'm pretty confident that nobody is using that yet, but you never know.

However, breaking the API is really necessary if you want to keep up with Elasticsearch on the server-side. There's probably nothing I can do besides trying to keep things simple and obvious for the users of Elastic.

So. Can you test that branch with your code and see if it works okay? Then I'll probably merge with master.

**Comment by nizsheanez** [comment]
I checked Phrase and Terms suggestors, our code base working well. 
Completition suggestor - checking other guy - in progress.
Context suggestor - we don't use it...

**Comment by olivere** [comment]
Closed by [this merge](https://github.com/olivere/elastic/commit/fc46ea6f0a3217045f5750b6e6581e7bfad41b28).

**Pull request closed without merging**
