### PR TITLE
added DoAsync method to elastic.v5

### PR DESCRIPTION
**Pull request by ppiccolo**
Backport DoAsync to update_by_query.go

### CODE REVIEW

**Comment by olivere** [comment]
Thanks for your support.

Can you please also backport the tests, e.g. [this one](https://github.com/olivere/elastic/blob/2b61967508bfe191518bf4648e3438c69a1ee5ea/update_by_query_test.go#L149-L189). Then I'll add it to the next release.

**Comment by ppiccolo** [comment]
Sure.

**Comment by olivere** [comment]
Will push 5.0.77 soon. Sorry for the loooong delay.

**Comment by ppiccolo** [comment]
no problem and thank you for you great work.

**Pull request merged**
