### PR TITLE
support Multi termvectors API

### PR DESCRIPTION
**Pull request by suzuken**
supports https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-multi-termvectors.html

### CODE REVIEW

**Comment by olivere** [comment]
That's looking really good, thank you for your support. :-)

Can you double check that all properties defined in the [REST API spec for `mtermvectors`](https://github.com/elastic/elasticsearch/blob/2.4/rest-api-spec/src/main/resources/rest-api-spec/api/mtermvectors.json) are available?

Also: Did you notice there's a generator that takes a [REST API spec file](https://github.com/elastic/elasticsearch/tree/2.4/rest-api-spec/src/main/resources/rest-api-spec/api) as input and emits Go code for a service as output? You can see it in the [generate-api branch](https://github.com/olivere/elastic/tree/generate-api/generator). It makes creating missing services a bit easier than doing everything manually.

**Comment by suzuken** [comment]
Thank you for your reply. 

> Can you double check that all properties defined in the REST API spec for mtermvectors are available?

Oh, OK. I'll see it.

> Also: Did you notice there's a generator that takes a REST API spec file as input and emits Go code for a service as output? You can see it in the generate-api branch. It makes creating missing services a bit easier than doing everything manually.

It seems good. This PR implemented by my hands, I'll try it.

**Comment by olivere** [comment]
It's okay. No need to change it if all properties are there. The generator is simply for creating a skeleton for you.

I'll integrate it with the next release. Thanks for being a contributor.

**Comment by suzuken** [comment]
Thank you for your comments. I've added some properties related [elasticsearch/mtermvectors.json at 2.4 · elastic/elasticsearch](https://github.com/elastic/elasticsearch/blob/2.4/rest-api-spec/src/main/resources/rest-api-spec/api/mtermvectors.json) .

**Comment by olivere** [comment]
So I've just added your PR. I've changed a few things; maybe you can double check if that makes sense.

Most changes are stylistic or fix a typo. However there's a significant change in verifying the request. In my understanding, it should be okay to call the `/_mtermvectors` endpoints in 3 possible ways (as described [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-multi-termvectors.html) and in the [REST API spec](https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/mtermvectors.json).

1. Index and type: `/{index}/{type}/_mtermvectors` (no docs in body required)
2. Index but no type: `/{index}/_mtermvectors` (pass docs with type in the body)
3. No index and no type: `/_mtermvectors` (pass docs in the body)

What's not possible is 4. No index but a type. I've changed the Validate func accordingly and implemented a test for that behavior.

I've also changed the call in `client.go` to not require index and type, i.e. change

```go
func (c *Client) MultiTermVectors(index, typ string) *MultiTermvectorService { ... }
```

... to ...

```go
func (c *Client) MultiTermVectors() *MultiTermvectorService { ... }
```

I will release a new version of Elastic later this evening. If something's wrong, we'll fix it in the next release.

**Comment by suzuken** [comment]
looks good to me. thanks! :)
2016/06/24 20:18 "Oliver Eilhard" <notifications@github.com>:

**Pull request closed without merging**
