### PR TITLE
Add regex field for completion suggester.

### PR DESCRIPTION
**Pull request by mnpritula**

### CODE REVIEW

**Comment by mnpritula** [comment]
Can anyone look at this pull request, please?

**Comment by olivere** [comment]
Sorry for the delay. Will do so over the next hours and days.

**Comment by olivere** [comment]
I refactored completion suggester to support all current options in [this commit](https://github.com/olivere/elastic/commit/ad8708e97f1d4e0c43372d1a1fd8c09fc2b1d4be) which will be released in 5.0.59. See the tests for usage, and report errors as you find them.

**Comment by mnpritula** [comment]
Thanks a lot! I don't really deserve to be enlisted in contributors though.

**Pull request closed without merging**
