### PR TITLE
Add index analyze API

### PR DESCRIPTION
**Pull request by huydx**
This PR implement index analyze API, and support v3 only. (target for release-branch.v3)
Please take a look @olivere.

Thank you in advance.

### CODE REVIEW

**Comment by olivere** [comment]
Sorry, I'm busy the next two weeks. Might take some time.

**Comment by olivere** [comment]
Just a few notices:

1. Can you please compare the list of parameters with those publically specified in the [REST API specification](https://github.com/elastic/elasticsearch/tree/2.4/rest-api-spec) of that endpoint?
2. You can use the [generate-api branch](https://github.com/olivere/elastic/tree/generate-api/generator) to generate a skeleton of your service given the REST API spec for that endpoint. You might need to update the REST API spec files there first. Compare that with your service implementation, which is presumably implemented manually.
3. I don't like the `Do` vs. `DoWithExplain`. Can we merge that into one and use a parameter to differentiate?

Thank you.

**Comment by huydx** [comment]
@olivere Thanks for your comments, really helpful informations.
1.2. I will take a look at REST API specification
3. Currently analyze api with explain set as true return completely different json, so merge it as one may require user to cast interface{} to appropriate type when get response, which seems not good. Do you have any idea?

**Comment by olivere** [comment]
It seems that the Java API will generate two embedded structures into the response. See [here](https://github.com/elastic/elasticsearch/blob/2.4/core/src/main/java/org/elasticsearch/action/admin/indices/analyze/AnalyzeResponse.java#L160). Can we do that?

**Comment by huydx** [comment]
Nice idea, two embedded structures seems fair.

**Comment by huydx** [comment]
@olivere fixed as your advice

**Comment by shouichi** [comment]
@olivere Could you take a look at this?

**Comment by olivere** [comment]
I'm sorry, I took some time off between christmas and new year. I'll be back next week, and hopefully get this merged soon. Thank you for your work on Elastic.

**Comment by olivere** [comment]
I recently added the Index Analyze API based on your original PR. I changed some things, e.g. 5.1.1 deprecated passing the parameters in the request (it wants them in the body instead), and did some formatting and documentation.

I will port this to elastic.v5 soon, and it will be part of the next releases of v3 and v5.

Thanks for being so patient, and thanks for your work on this PR.

**Pull request closed without merging**
